### PR TITLE
PCCE: 30.03 Updates files

### PR DESCRIPTION
**Pull request by ssugandh**
## Description
PCCE 30.03 minor release output

## Motivation and Context
Minor release 30.03 output

## How Has This Been Tested?
Tested locally

## Screenshots (if appropriate)
Screenshot 2023-07-19 at 11 45 15 AM

## Types of changes
- New feature (non-breaking change which adds functionality)

## Checklist
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes if appropriate.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ssugandh** [comment]
@blindaa121 and @sserrata : Can you please see if this branch can be approved and merged to master for publishing Prisma Cloud Compute Maxwell Update 3 live?

**Comment by blindaa121** [comment]
> @blindaa121 and @sserrata : Can you please see if this branch can be approved and merged to master for publishing Prisma Cloud Compute Maxwell Update 3 live?

Hi @ssugandh, I'm still able to reproduce the issue on this PR so were not able to merge this quite yet

**Comment by ssugandh** [comment]
Hi Bryan,

My build was successful before https://pan-dev-f1b58--pr440-a9x16ojh.web.app
but now when I run it is failing again.
Any PR that I create has this issue.

The Compute release output is stuck. How can we resolve this?

Thanks,
Saurabh

**Comment by ssugandh** [comment]
@blindaa121 : Can you approve and merge this now? Build is fine, I'm not sure what else is remaining.

**Comment by sserrata** [comment]
@ssugandh, I was able to build the entire site using a canary release of the OpenAPI docs plugin. Can you please spot check the API docs to ensure everything rendered as expected?

**Comment by sserrata** [comment]
Here is the link to the preview: https://pan-dev-f1b58--pr439-nhetr7ni.web.app/

This is the PR: https://github.com/PaloAltoNetworks/pan.dev/pull/439

**Comment by ssugandh** [comment]
Hi Steven,

Yes, all changes are there. Thanks for your continued support!

So, you mean that you staged changes in iterations to achieve this output?

May I know what was the reason that caused this disruption? Was that too
much load for MDX files or modules?

I would want to avoid anything that caused it.

Thanks,
Saurabh

**Comment by sserrata** [comment]
No, it's building the entire site in one run, just as before. The difference is that we updated the OpenAPI docs plugin to compress the JSON metadata needed to render the API demo panel. This change should allow pan.dev to continue to scale for the time being, but I would still recommend pruning older Compute/CWPP releases whenever possible.

The root cause of the build errors is that the site grew large enough to exceed the maximum file size supported by node, which is 1GB. With the new metadata compression in place, we hope to see a 30-50% reduction in overall bundle size.

**Comment by ssugandh** [comment]
@sserrata @blindaa121 : If everything is alright, can you please approve and merge?

**Comment by manukumar6** [comment]
@sserrata, we are finalizing how to prune the PCCE API Ref. 

In the meantime, if this build or [439](https://github.com/PaloAltoNetworks/pan.dev/pull/439) is generating, please proceed with either of the two MRs, so that users have access to the latest docs.

**Pull request closed without merging**
